---
title: Make a Crumble robot head
hero_image: images/banner.png
description: make-crumble-robot-head description
version: 4
listed: true
copyedit: true
last_tested: '2019-06-26'
steps:
- title: Introduction
- title: The robot head
- title: Prepare the servo
  completion:
  - engaged
- title: The pushrod mechanism
- title: Wire servo to Crumble
- title: Find servo angles
- title: Open and close sequence
- title: 'Challenge: randomise your sequence'
  challenge: true
- title: Slow moves
- title: Multiple sequences
  completion:
  - internal
- title: 'Challenge: random sequence selector'
  challenge: true
- title: What next?
