title: make-crumble-robot-head
hero_image: images/banner.png
description: make-crumble-robot-head description
version: 4
listed: false
copyedit: false
last_tested: "2019-06-26"
steps:
  - title: Introduction
  - title: The robot head
  - title: Preparing the servo
  - title: The pushrod mechanism
  - title: Wiring servo to Crumble
  - title: Finding servo angles
  - title: s7
  - title: s8
